### PR TITLE
Build complete home page except testimonials section as directed in the issue and made it responsive for all screen sizes

### PR DESCRIPTION
**Pull request by Yash-Chauhan09**

### CODE REVIEW

**Comment by Yash-Chauhan09** [comment]
#29 ✔

**Comment by iamparasbansal** [comment]
your home.js was having a lot of errors. (maybe due to merge conflicts with some other push). Please make a fresh pull request again.

**Comment by iamparasbansal** [comment]
@Yash-Chauhan09

**Comment by Yash-Chauhan09** [comment]
@iamparasbansal  That's so strange because it's working fine in my local machine, still I'll see what I can do .👍

**Comment by iamparasbansal** [comment]
Yeah, it maybe because we got a faulty pull request yesterday which messed the whole code. Although everything was recovered expect your home,js So, a fresh pull request will be good.

**Pull request merged**
