### PR TITLE
Fixed contact

### PR DESCRIPTION
**Pull request by Nirpendra09**
The contact page is made. It has a form with some animation and made using material ui . And all the social media handles are also there on page and shown in a creative way..

### CODE REVIEW

**Comment by hkaur008** [comment]
resolve ! conflicts

**Comment by hkaur008** [comment]
Resolve conflict pls!

**Comment by Nirpendra09** [comment]
Done

**Comment by hkaur008** [comment]
pls send pull request again , due to solve issue , we have to revert it .

**Pull request merged**
