### PR TITLE
Made upcoming event card for event page

### PR DESCRIPTION
**Pull request by Rishabhraghwendra18**
Issue - #42 
Description -
Made upcoming event card for event page . It's also responsive

### CODE REVIEW

**Comment by hkaur008** [comment]
solve conflict

**Comment by iamparasbansal** [comment]
Please try to make your commits concise. For example, added padding, added text, added background, etc. can be done in 1 commit.

**Comment by iamparasbansal** [comment]
@Rishabhraghwendra18  I have merged your pull request for now but this work was already done. **Please sync your local repo with remote.** And also try to make your commits concise as much as possible. For example, added padding, added text, divs position, etc. can be done in one commit.

**Comment by Rishabhraghwendra18** [comment]
@iamparasbansal . I thought no one was working on this as the issue was open and no one was assigned to it . Ok..I will take care of this like adding padding , added text in 1 commit .

**Comment by Rishabhraghwendra18** [comment]
@iamparasbansal btw many I know why you have reverted my changes ?

**Comment by iamparasbansal** [comment]
Bro your code was added and It will be counted as a contribution to your stats. But it was already done so I have to revert the changes in order to remove duplicated work.

**Pull request merged**
